rename and improve

diff --git a/cfg/gendsp.sh.in b/cfg/gendsp.sh.in
--- a/cfg/gendsp.sh.in
+++ b/cfg/gendsp.sh.in
@@ -29,26 +29,109 @@
 # 20041214 larsa
 
 me=$0
+
+
+# **************************************************************************
+# useful sed commands
+
+sed_d2u='s,\\,/,g' # dos2unix path delimiter switching
+sed_u2d='s,/,\\,g' # unix2dos path delimiter switching
+
+
+# **************************************************************************
+# useful autoconf variables - added for optimization/simplification reasons
+
+prefix="@prefix@"
+build_dir="@abs_top_builddir@"
+src_dir="@abs_top_srcdir@"
+ac_unique_file="@ac_unique_file@"
+sim_ac_relative_src_dir="@sim_ac_relative_src_dir@"
+sim_ac_relative_src_dir_p="@sim_ac_relative_src_dir_p@"
+
+me_u=`echo $me | sed $sed_d2u`
+medir_u=`echo $me_u | sed 's,[^/]*$,,g'`
+srcdir_u=`cd $medir_u/..; pwd | sed $sed_d2u`
+thisdir_u=`pwd | sed $sed_d2u`
+
+if $sim_ac_relative_src_dir_p; then
+  if test -f $srcdir_u/$sim_ac_relative_src_dir/$ac_unique_file; then
+    :
+    # things are in place
+  else
+    echo >&2 "$me: error: directories have been moved relative to each other"
+    echo >&2 "   since the last configure run."
+    exit
+  fi
+else
+  echo >&2 "$me: error: dsp generation is not supported when absolute paths"
+  echo >&2 "   are necessary to locate files."
+  exit
+fi
+
+# **************************************************************************
+# preliminary variable exploration
+
+# echo "me:       $me_u"
+# echo "medir:    $medir_u"
+# echo "srcdir:   $srcdir_u"
+# echo "thisdir:  $thisdir_u"
+
+# exit
+
 # run this where needed: me=`echo $me | sed 's%^.*/%%g'`
 
-if test x"$1" = x"--register-public-header"; then
-  sourcedir=$2
-  builddir=$3
-  studiofile=$4
-  headerfile=$5
-  # installpath=`CYGWIN= cygpath -w "$6" 2>/dev/null || echo "$6"`
+# **************************************************************************
+# The following block (the --registar-public-header part) generates
+# 1) the public headers part of the .dsp file
+# 2) the install*headers.bat file
+# It is invoked from a "make ... install-data"-command far down in this script
 
+if test x"$1" = x"--register-public-header"; then
+  studiofile=$2
+  headerfile=$3
+  installpath=$4
+  finalheader=`echo "$installpath" | sed -e "s,.*$prefix/\\(include\\|data\\)/,%COINDIR%/\\1/," -e "s,/\\./,/,g" -e "$sed_u2d"`
+  sim_ac_relative_src_dir_q=`echo "@sim_ac_relative_src_dir@" | sed -e 's,\.,\\\\.,g'`
+
+  # echo "========================="
+  # echo "source dir:   $src_dir"
+  # echo "build dir:    $build_dir"
+  # echo "install dir:  $installpath"
+  # echo "header:       $headerfile"
+
+  # echo "relative:     $sim_ac_relative_src_dir"
+
+  tested=true
   case $headerfile in
-  [a-z]:* | /* )
-    # absolute path
+  *$sim_ac_relative_src_dir/* )
+    headerfile=`echo $headerfile | sed -e "s%.*$sim_ac_relative_src_dir_q%$sim_ac_relative_src_dir%"`
     ;;
-  * )
-    # relative path
-    headerfile="`pwd`/$headerfile"
+  $build_dir/* )
+    tested=false
+    echo "EXPLICIT IN BUILD DIR"
+    headerfile=`echo $headerfile | sed -e "s%$build_dir/%%"`
+    ;;
+  $src_dir* )
+    tested=false
+    echo "EXPLICIT IN SOURCE DIR - CONVERT TO RELATIVE"
+    headerfile=`echo $headerfile | sed -e "s%$src_dir%$sim_ac_relative_src_dir%"`
+    ;;
+  *)
+    headerfile=`pwd`/$headerfile
+    headerfile=`echo $headerfile | sed -e "s%$build_dir/%%"`
     ;;
   esac
-  headerfile=`CYGWIN= cygpath -w "$headerfile" 2>/dev/null || echo "$headerfile"`
 
+  # echo "final header: $headerfile"
+  # echo "FINAL header: $finalheader"
+  # echo "========================="
+
+  headerfile=`echo $headerfile | sed -e "$sed_u2d"`
+
+  if $tested; then :; else
+    echo "untested case - manual inspection required";
+    exit 1;
+  fi
 
   echo "# Begin Source File" >>"$studiofile"
   echo "" >>"$studiofile"
@@ -58,16 +141,19 @@ if test x"$1" = x"--register-public-header"; then
   # and the installation script
   installheadersfile=`echo $studiofile | sed -e 's,\([^\\/0-9]*\)[0-9][^\\/]*\.dsp,install\1headers.bat,'`
 
-  sourcedirq=`echo "$sourcedir" | sed -e 's,\\\\,\\\\,g'`
-  builddirq=`echo "$builddir" | sed -e 's,\\\\,\\\\,g'`
-  relheader=`echo "$headerfile" | sed -e "s,$builddirq,.,g" -e "s,$sourcedirq,..\\\\..,g" -e 's,\\\\,\\\\\\\\,g'`
-  finalheader=`echo "$relheader" | sed -e 's,.*include,include,g'`
-  relheader=`echo "$relheader"`
-  finalheader=`echo "$finalheader"`
-  
-  echo "copy $relheader %COINDIR%\\$finalheader" >>"$installheadersfile"
+  # sourcedirq=`echo "$sourcedir" | sed -e 's,\\\\,\\\\,g'`
+  # builddirq=`echo "$builddir" | sed -e 's,\\\\,\\\\,g'`
+  # relheader=`echo "$headerfile" | sed -e "s,$builddirq,.,g" -e "s,$sourcedirq,..\\\\..,g" -e 's,\\\\,\\\\\\\\,g'`
+  # finalheader=`echo "$relheader" | sed -e 's,.*include,include,g'`
+  # relheader=`echo "$relheader"`
+  # finalheader=`echo "$finalheader"`
+
+  echo "copy $headerfile $finalheader >nil:" >>"$installheadersfile"
   exit 0
 fi
+
+# **************************************************************************
+#
 
 # this variable should contain the list of variables we want to use in the
 # project file setup, instead of just having the values.
@@ -311,12 +397,10 @@ case "$outputfile" in
   builddir=`echo "$studiofile" | sed -e 's%/[^/]*$%%'`
   builddir_unix=$builddir
   builddir=`CYGWIN= cygpath -w "$builddir" 2>/dev/null || echo "$builddir"`
-  builddirfixed=`echo "$builddir" | sed -e 's/\\\\/\\\\\\\\/g'`
 
   sourcedir=`echo "$0" | sed -e 's%/cfg/gendsp.sh$%%' -e 's,\\cfg\\gendsp.sh,,'`
   sourcedir_unix=$sourcedir
   sourcedir=`CYGWIN= cygpath -w "$sourcedir" 2>/dev/null || echo "$sourcedir"`
-  sourcedirfixed=`echo "$sourcedir" | sed -e 's/\\\\/\\\\\\\\/g'`
 
   # PUBLIC HEADERS
   # To get the list of public header files, we run "make install" into a
@@ -326,8 +410,10 @@ case "$outputfile" in
   echo '# Begin Group "Public Headers"' >>"$studiofile"
   echo "" >>"$studiofile"
   echo '# PROP Default_Filter "h"' >>"$studiofile"
-  ( cd $builddir_unix; make INSTALL_HEADER="$0 --register-public-header $sourcedirfixed $builddirfixed $studiofile" DESTDIR=/tmp/coin-dsp install-data )
-  rm -rf /tmp/coin-dsp
+  tmpdir=/tmp/dsp-install.tmp
+  ( cd $builddir_unix;
+    make INSTALL_HEADER="$0 --register-public-header $studiofile" DESTDIR="$tmpdir" install-data )
+  rm -rf $tmpdir
   echo '# End Group' >>"$studiofile"
 
   # PRIVATE HEADERS
